### ISSUE TITLE
v3.2.0 tag needed on npmjs

### ISSUE THREAD

**Issue by DylanC** [nearform/node-clinic-common#32]
In order for Flame and possibly other Clinic tools to display correctly you would need the v3.2.0 tag on https://www.npmjs.com/package/@nearform/clinic-common. Then update the package.json files to that new version.

clinic-common v3.2.0
![latest](https://user-images.githubusercontent.com/4488048/84046766-6dca6c00-a9a2-11ea-9dd4-26515dc1af56.png)

clinic-common v3.1.0 (current)
![image](https://user-images.githubusercontent.com/4488048/84046650-496e8f80-a9a2-11ea-9502-01f8efb54da0.png)

@jasnell

**Comment by jasnell** [comment]
Ah, are the errors then just a missed publish to npm?

**Comment by DylanC** [comment]
@jasnell Working perfectly now in master. (v6.0.2) :tada:
